### PR TITLE
Convert chart to Helm 3 and update documentation

### PR DESCRIPTION
**Pull request by dgrove-oss**

### CODE REVIEW

**Comment by dgrove-oss** [comment]
Created WIP PR as requested by @chetanmeh.  This PR is "functionally complete", but there is still quite a bit more validation and documentation that could be done in values.schema.json.

Once I replicate the non-trivial subset of  all the`description` lines from values-metadata.yaml into values.schema.json, I will remove values-metadata.yaml.

**Comment by dgrove-oss** [comment]
@chetanmeh -- this PR is ready for review. Please take a look when you have a change.

**Comment by neerajmangal** [comment]
Sorry for the late response. I am taking a look and validating with helm3.

**Comment by dgrove-oss** [comment]
Thanks @neerajmangal -- I went ahead and merged the PR.

**Pull request merged**
