### PR TITLE
install package catalog using `wsk project deploy`

### PR DESCRIPTION
**Pull request by dgrove-oss**

### CODE REVIEW

**Comment by dgrove-oss** [comment]
Installing the catalog as per this PR results in crashes from the cli.  Need to investigate further...
```
/openwhisk-catalog/packages /
Installing OpenWhisk packages
Deploying /openwhisk-catalog/packages/combinators/ with pid 113
Deploying /openwhisk-catalog/packages/github/ with pid 114
Deploying /openwhisk-catalog/packages/slack/ with pid 115
Deploying /openwhisk-catalog/packages/utils/ with pid 116
Deploying /openwhisk-catalog/packages/watson-speechToText/ with pid 117
Deploying /openwhisk-catalog/packages/watson-textToSpeech/ with pid 119
Deploying /openwhisk-catalog/packages/weather/ with pid 124
Deploying /openwhisk-catalog/packages/websocket/ with pid 125
Deploying /openwhisk-catalog/packages/samples/ with pid 129
runtime error: invalid memory address or nil pointer dereference
Application exited unexpectedly
runtime error: invalid memory address or nil pointer dereference
Application exited unexpectedly
runtime error: invalid memory address or nil pointer dereference
Application exited unexpectedly
113 finished with status 0
runtime error: invalid memory address or nil pointer dereference
Application exited unexpectedly
runtime error: invalid memory address or nil pointer dereference
Application exited unexpectedly
runtime error: invalid memory address or nil pointer dereference
Application exited unexpectedly
114 finished with status 0
115 finished with status 0
116 finished with status 0
117 finished with status 0
119 finished with status 0
runtime error: invalid memory address or nil pointer dereference
Application exited unexpectedly
runtime error: invalid memory address or nil pointer dereference
Application exited unexpectedly
runtime error: invalid memory address or nil pointer dereference
Application exited unexpectedly
124 finished with status 0
125 finished with status 0
129 finished with status 0
open catalog ERRORS = 0
```

**Comment by dgrove-oss** [comment]
Finally can make this change.  Bug fix included in wsk 1.0.0 allows us to use `wsk project` to deploy catalog.

**Comment by chetanmeh** [comment]
Would be good to link the wsk issue which was fixed

**Comment by dgrove-oss** [comment]
Good point.  For the record the issues in wskdeploy was https://github.com/apache/openwhisk-wskdeploy/issues/1050, which was fixed in wskdeploy https://github.com/apache/openwhisk-wskdeploy/pull/1059.  The root cause a bug in openwhisk-client-go, which was fixed in https://github.com/apache/openwhisk-client-go/pull/123

**Pull request merged**
