### PR TITLE
Fix to check if affinity is enabled

### PR DESCRIPTION
**Pull request by upgle**
## Description

This PR fixes to check if the affinity is enabled in the user-events and invoker pod.

### CODE REVIEW

**Comment by upgle** [comment]
@dgrove-oss 
Thank you for your review. The affinity can not be allowed in some k8s environments. 
> Error: admission webhook "k8s-cluster" denied the request: node affinity is not allowed

And all microservices are checking affinity is enabled or not. But I couldn't deploy it because user-events service and invoker service didn't check that.

I think affinity can be ignored for testing purposes if  `Values.affinity` is disabled (e.g. single node). What do you think?

- [nginx](https://github.com/apache/openwhisk-deploy-kube/blob/b0a558c4591df0bc75cbf9198584a18c88a7e1f0/helm/openwhisk/templates/nginx-pod.yaml#L39)
   https://github.com/apache/openwhisk-deploy-kube/blob/b0a558c4591df0bc75cbf9198584a18c88a7e1f0/helm/openwhisk/templates/nginx-pod.yaml#L39
- [couchdb](https://github.com/apache/openwhisk-deploy-kube/blob/b0a558c4591df0bc75cbf9198584a18c88a7e1f0/helm/openwhisk/templates/couchdb-pod.yaml#L39)
  https://github.com/apache/openwhisk-deploy-kube/blob/b0a558c4591df0bc75cbf9198584a18c88a7e1f0/helm/openwhisk/templates/couchdb-pod.yaml#L39
- [controller](https://github.com/apache/openwhisk-deploy-kube/blob/dc889a2e6a2de8a21daece2afd105e63329498be/helm/openwhisk/templates/controller-pod.yaml#L48)
https://github.com/apache/openwhisk-deploy-kube/blob/dc889a2e6a2de8a21daece2afd105e63329498be/helm/openwhisk/templates/controller-pod.yaml#L48

**Comment by dgrove-oss** [comment]
DockerContainerFactory is of dwindling usefulness, but I do think we should either require affinity to be enabled when using DockerContainerFactory or make some changes to the documentation to make it clear what is happening.  In particular we emphasize labeling the subset of nodes for invokers to use (https://github.com/apache/openwhisk-deploy-kube#initial-setup). If we are going to ignore that when affinity is disabled, we should clearly document that so that people understand that unless you are just kicking the tires on a single node cluster, its not a good configuration to use.

**Comment by upgle** [comment]
There was an annotation about the affinity option, so I expected it will disable all microservices' affinity and anti-affinity configurations if I disable this option. But It didn't.
```
# Used to define pod affinity and anti-affinity for the Kubernetes scheduler.
# If affinity.enabled is true, then all of the deployments for the OpenWhisk
# microservices will use node and pod affinity directives to inform the
# scheduler how to best distribute the pods on the available nodes in the cluster.
affinity:
  enabled: true
```

I'll update the document more clearly.

**Comment by upgle** [comment]
I think https://github.com/apache/openwhisk-deploy-kube#initial-setup this document is related to the [user-pod-node-affinity](https://github.com/apache/openwhisk/blob/fb6c779da576e9e4d32a6d7501a4d2031ab1dbf3/core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/WhiskPodBuilder.scala#L46) of the Invoker service. And this PR is for disabling affinity of the monitoring and invoker service (not user pod node).

I've updated the README document about this.

**Comment by dgrove-oss** [comment]
@upgle when you get a chance, could you rebase to latest master?  I just merged a change (#612) that disabled a few test cases so we have a better chance of getting a clean TravisCI run.

**Comment by upgle** [comment]
@dgrove-oss I've rebased it to the latest master. And all test cases passed 👍

**Pull request merged**
